collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3875707
  brandStrength: 0.2278766
  rhythmicContrast: 0.8408499
  brandColors:
    - '#111111'
    - '#FEFEFE'
    - '#7A7A7A'
    - '#393939'
    - '#CBCBCB'
  lightness: 0.532007
typography_spectrum: 0.6039426
layout_spectrum: 1
name: TanjaSpirit
